//#include <Windows.h>

#define PROFILES_PATH "C:\\Users\\Mark\\Documents\\Quantum Gas Assembly Control\\Profiles\\"
#define DEFAULT_SCRIPT_FOLDER_PATH "..."

#define MASTER_SCRIPT_EXTENSION ".mScript"
#define NIAWG_SCRIPT_EXTENSION ".nScript"
#define AGILENT_SCRIPT_EXTENSION ".aScript"
#define HORIZONTAL_ORIENTATION "Horizontal"
#define VERTICAL_ORIENTATION "Vertical"

#define HORIZONTAL_EXTENSION ".hConfig"
#define VERTICAL_EXTENSION ".vConfig"
#define EXPERIMENT_EXTENSION ".eConfig"
#define CATEGORY_EXTENSION ".catConfig"
#define SEQUENCE_EXTENSION ".sConfig"

#define NULL_SEQUENCE "NULL_SEQUENCE"


#define SYNTAX_TIMER_ID 500
#define SYNTAX_TIMER_LENGTH 1000

// All ttl Button IDs
#define ID_TTL_BUTTON_A1 1001
// The next 63 numbers are reserved for the other TTLs!
#define ID_TTL_BUTTON_HOLD 1065
#define ID_DAC_EDIT_1 1066
// the next ??? numbers are reserved for the other DACs!
#define ID_DAC_SET_BUTTON 1087
#define ID_VAR_LIST 1088
#define ID_VARIABLE_ADD 1089
#define ID_VARIABLE_DELETE 1090
#define IDC_VARIABLES_LISTVIEW 1091
#define IDC_SEQUENCE_DISPLAY 1092
#define IDC_SAVE_EXPERIMENT_INDICATOR_BUTTON 1093
#define IDC_SAVE_CATEGORY_INDICATOR_BUTTON 1094
#define IDC_EXPERIMENT_COMBO 1095
#define IDC_CATEGORY_COMBO 1096
#define IDC_SAVE_CONFIGURATION_INDICATOR_BUTTON 1097
#define IDC_ORIENTATION_COMBO 1098
#define IDC_CONFIGURATION_COMBO 1099
#define IDC_SEQUENCE_TEXT 1100
#define IDC_SEQUENCE_COMBO 1101
#define IDC_EXPERIMENT_NOTES_HEADER 1102
#define IDC_EXPERIMENT_NOTES 1103
#define IDC_CATEGORY_NOTES_HEADER 1104
#define IDC_CATEGORY_NOTES 1105
#define IDC_CONFIGURATION_NOTES_HEADER 1106
#define IDC_CONFIGURATION_NOTES 1107

